server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: stalk-backend
  
  datasource:
    url: jdbc:mysql://localhost:3306/stalk_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET:stalkSecretKeyForJWTTokenGenerationAndValidation2024}
  expiration: 86400000 # 24 hours

logging:
  level:
    com.stalk: DEBUG
    org.springframework.security: DEBUG 